---
- name: Check that security group has a description
  assert:
    that: "'description' in security_group.data"
    quiet: yes
  when: security_group.name != 'default'

- name: Check security group rules
  include_tasks: check_security_group_rule.yml
  loop: "{{ security_group.data['rules'] | default([]) }}"
  loop_control:
    loop_var: rule
    index_var: rule_idx
    label: "{{ security_group.name }}:{{ rule_idx }}"
