- name: Imitate initialization of a cluster
  hosts: app
  gather_facts: no
  tasks:
    - name: Install nginx
      package: name=nginx state=installed

    - name: Imitate start of cluster from one node
      command: hostname
      run_once: yes

    - name: Start and enable nginx
      service: name=nginx state=started enable=yes
