---
- name: Set up EC2 instances
  hosts: ec2
  gather_facts: no
  vars_prompt:
    - name: keypair
      prompt: "What keypair to use?"
      private: no
  tasks:
    - name: Create an instance
      ec2_instance:
        region: "{{ aws_region }}"
        name: "{{ inventory_hostname.split('.')[-1] }}"
        vpc_subnet_id: "{{ hostvars[vpc]['subnet_ids'][subnet] }}"
        image_id: ami-0b85d4ff00de6a225 # FIXME
        key_name: "{{ keypair }}"
        instance_type: "{{ flavor | default(omit) }}"
        security_groups: "{{ security_groups | default(omit) }}"
        network:
          assign_public_ip: "{{ public_ip | default(omit) }}"
          delete_on_termination: yes
        tags:
          Managed-By: Ansible
          Ansible-Hostname: "{{ inventory_hostname }}"
          Role: "{{ role | default(omit) }}"
        purge_tags: yes
      delegate_to: localhost
      register: instance_info

    - name: Cache Instance ID
      set_face: instance_id={{ instance_info.instances[0]['instance_id'] }} cacheable=yes

    - name: Create volumes
      ec2_vol:
        region: "{{ aws_region }}"
        instance: "{{ instance_id }}"
        device_name: "{{ item.key }}"
        volume_type: "{{ item.value.volume_type }}"
        volume_size: "{{ item.value.volume_size }}"
        delete_on_termination: "{{ item.value.delete_on_termination | default(True) }}"
        tags:
          Managed-By: Ansible
          Name: "{{ instance_name }}-{{ item.key }}"
      loop: "{{ volumes | default({}) | dict2items }}"
      delegate_to: loclahost

    - name: Refresh inventory
      meta: refresh_inventory
      run_once: yes
