---
- block:
  - name: Get VPC information
    ec2_vpc_net_info:
      region: "{{ aws_region }}"
      filters:
        cidr: "{{ cidr }}"
        tag:Name: "{{ name }}-vpc"
    register: _vpcs
  - name: Cache VPC ID
    set_fact: vpc_id={{ _vpcs['vpcs'][0]['vpc_id'] }} cacheable=yes
  when: vpc_id is not defined

- block:
  - name: Get internet gateway information
    ec2_vpc_igw_info:
      region: "{{ aws_region }}"
      filters:
        attachment.vpc-id: "{{ vpc_id }}"
        tag:Name: "{{ name }}-igw"
    register: _igws
  - name: Cache Internet Gateway ID
    set_fact: igw_id={{ _igws['internet_gateways'][0]['internet_gateway_id'] }} cacheable=yes
  when: igw_id is not defined

- block:
  - name: Get subnets information
    ec2_vpc_subnet_info:
      region: "{{ aws_region }}"
      filters:
        vpc-id: "{{ vpc_id }}"
        cidr: "{{ item.value['cidr'] }}"
        tag:Name: "{{ name }}-{{ item.key }}-subnet"
    loop: "{{ subnets | dict2items }}"
    register: _subnets
  - name: Cache Subnet ID’s
    set_fact:
      subnet_ids: >
        {{
            subnet_ids
            | default({})
            | combine({ item['subnets'][0]['tags']['Name']: item['subnets'][0]['id'] })
        }}
      cacheable: yes
    loop: "{{ _subnets.results }}"
