---
aws_region: "{{ inventory_hostname.split('.')[0] }}"
vpc_name: "{{ inventory_hostname.split('.')[1] }}"
instance_name: "{{ inventory_hostname.split('.', 2)[2] }}"
vpc: "{{ aws_region }}.{{ vpc_name }}"
