---
- hosts: vpcs
  gather_facts: no
  tasks:
    - include_tasks: facts/vpc.yml

    - name: Find all security groups in VPC
      ec2_group_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
      register: security_groups_output

    - name: Remove obsolete security groups (managed by Ansible)
      ec2_group:
        region: "{{ aws_region }}"
        group_id: "{{ item.group_id }}"
        state: absent
      when: >
        item.tags['Managed-By'] | default(none) == 'Ansible'
        and item.group_name not in security_groups
      loop: "{{ security_groups_output.security_groups }}"
      loop_control:
        label: "{{ item.group_name }} ({{ item.group_id }})"
